#
# QNick configuration guide
#

# Enables or disables the `nick` command (true = enabled, false = disabled)
# May be useful if using a plugin which uses the QNickAPI
command: true

# Changes a users name to their nick (if found) on join (true = enabled, false = disabled)
# May be useful if using a plugin which uses the QNickAPI
changenameonjoin: true

# SQL, if true uses an SQL database to store nicknames
# Set to false to use PDC
sql: false

# These options only apply if SQL is enabled
sqloptions:
  host: "127.0.0.1"
  port: 3306
  db: "yourDB"
  username: "username"
  password: "password"

#
# Debug options
#

# Enable/disable API access (true = enabled, false = disabled)
# May be useful to server owners when debugging plugin issues
apienabled: true